from PyQt5 import QtCore, QtGui, QtWidgets

from settingUI import Ui_Form
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1327, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(90, 40, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(100)
        self.setting.setFont(font)
        self.setting.setObjectName("setting")
        self.nameproject = QtWidgets.QLabel(self.centralwidget)
        self.nameproject.setGeometry(QtCore.QRect(60, 105, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameproject.setFont(font)
        self.nameproject.setObjectName("nameproject")
        self.dgvMachineStatus = QtWidgets.QTableWidget(self.centralwidget)
        self.dgvMachineStatus.setGeometry(QtCore.QRect(60, 130, 1202, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dgvMachineStatus.sizePolicy().hasHeightForWidth())
        self.dgvMachineStatus.setSizePolicy(sizePolicy)
        self.dgvMachineStatus.setMinimumSize(QtCore.QSize(1070, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dgvMachineStatus.setFont(font)
        self.dgvMachineStatus.setAutoFillBackground(True)
        self.dgvMachineStatus.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dgvMachineStatus.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.dgvMachineStatus.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.dgvMachineStatus.setObjectName("dgvMachineStatus")
        self.dgvMachineStatus.setColumnCount(10)
        self.dgvMachineStatus.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.dgvMachineStatus.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        # self.dgvMachineStatus.setHorizontalHeaderItem(10, item)
        self.lbStatus = QtWidgets.QLabel(self.centralwidget)
        self.lbStatus.setGeometry(QtCore.QRect(980, 40, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lbStatus.setFont(font)
        self.lbStatus.setObjectName("lbStatus")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 90, 1331, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(950, -10, 20, 111))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(240, 0, 20, 101))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(500, 20, 300, 51))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.nameproject.raise_()
        self.dgvMachineStatus.raise_()
        self.lbStatus.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.name.raise_()
        self.setting.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuSystem = QtWidgets.QMenu(self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())          
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SERVER MET"))
        self.setting.setText(_translate("MainWindow", "SETTING"))
        self.nameproject.setText(_translate("MainWindow", "Auto machines line\'s status"))
        item = self.dgvMachineStatus.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME MACHINE"))
        item = self.dgvMachineStatus.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.dgvMachineStatus.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IP ADDRESS"))
        item = self.dgvMachineStatus.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TIME"))
        item = self.dgvMachineStatus.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "GREEN"))
        item = self.dgvMachineStatus.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "YELLOW"))
        item = self.dgvMachineStatus.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "RED"))
        item = self.dgvMachineStatus.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "IDLE"))
        item = self.dgvMachineStatus.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ERROR STATUS"))
        item = self.dgvMachineStatus.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "OUTPUT"))
        # item = self.dgvMachineStatus.horizontalHeaderItem(10)
        # item.setText(_translate("MainWindow", "END PORT"))
        self.lbStatus.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Mất kết nối với Sever</span></p></body></html>"))
        self.name.setText(_translate("MainWindow", "SERVER MET"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.setting.clicked.connect(self.opensetting)
        

    def opensetting(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()