# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import json
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 414)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(100, 10, 261, 391))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(0, 200, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(0, 230, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(0, 260, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(170, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.lineEdit.setObjectName("ipServer")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 50, 113, 20))
        self.lineEdit_2.setObjectName("dbName")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.lineEdit_3.setObjectName("timeUpdate")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 110, 113, 20))
        self.lineEdit_4.setObjectName("factory")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 140, 113, 20))
        self.lineEdit_5.setObjectName("line")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 170, 113, 20))
        self.lineEdit_6.setObjectName("projectName")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 200, 113, 20))
        self.lineEdit_7.setObjectName("owner")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 230, 113, 20))
        self.lineEdit_8.setObjectName("chamberMonitor")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 260, 113, 20))
        self.lineEdit_9.setObjectName("chamberMonitorQUA")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(0, 290, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 290, 113, 20))
        self.lineEdit_10.setObjectName("totalMachine")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 320, 113, 20))
        self.lineEdit_11.setObjectName("UPH")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(0, 320, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.apply_setting)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SETTING"))
        self.label.setText(_translate("Form", "IP server"))
        self.label_2.setText(_translate("Form", "DB Name"))
        self.label_3.setText(_translate("Form", "Time Update"))
        self.label_4.setText(_translate("Form", "Factory"))
        self.label_5.setText(_translate("Form", "Line"))
        self.label_6.setText(_translate("Form", "Project Name"))
        self.label_7.setText(_translate("Form", "Owner"))
        self.label_8.setText(_translate("Form", "Chamber moniter"))
        self.label_9.setText(_translate("Form", "Chamber moniter QUA"))
        self.pushButton.setText(_translate("Form", "Apply"))
        self.label_10.setText(_translate("Form", "Total machine"))
        self.label_11.setText(_translate("Form", "UPH"))
        
        self.loadconfig()
    def loadconfig(self):
        try:
            with open('data.json', 'r') as file:
                data = json.load(file)
                self.lineEdit.setText(data.get('ipServer', ''))
                self.lineEdit_2.setText(data.get('dbName', ''))
                self.lineEdit_3.setText(data.get('timeUpdate', ''))
                self.lineEdit_4.setText(data.get('factory', ''))
                self.lineEdit_5.setText(data.get('line', ''))
                self.lineEdit_6.setText(data.get('projectName', ''))
                self.lineEdit_7.setText(data.get('owner', ''))
                self.lineEdit_8.setText(data.get('chamberMonitor', ''))
                self.lineEdit_9.setText(data.get('chamberMonitorQUA', ''))
                self.lineEdit_10.setText(data.get('totalMachine', ''))
                self.lineEdit_11.setText(data.get('UPH',''))
                
        except FileNotFoundError:
            pass  # File not found, no data to load
    def updateconfig(self):
         # Get the text from LineEdit
        new_text = self.lineEdit.text()
        new_text2 = self.lineEdit_2.text()
        new_text3 = self.lineEdit_3.text()
        new_text4 = self.lineEdit_4.text()
        new_text5 = self.lineEdit_5.text()
        new_text6 = self.lineEdit_6.text()
        new_text7 = self.lineEdit_7.text()
        new_text8 = self.lineEdit_8.text()
        new_text9 = self.lineEdit_9.text()
        new_text10= self.lineEdit_10.text()
        new_text11= self.lineEdit_11.text()
        # Load existing data from data.json
        try:
            with open('data.json', 'r') as file:
                data = json.load(file)
        except FileNotFoundError:
            data = {}  # If file doesn't exist, create an empty dictionary

        # Update data with new value
        data['ipServer'] = new_text  # Replace 'key' with your actual key
        data['dbName'] = new_text2
        data['timeUpdate'] = new_text3
        data['factory'] = new_text4
        data['line'] = new_text5
        data['projectName'] = new_text6
        data['owner'] = new_text7
        data['chamberMonitor'] = new_text8
        data['chamberMonitorQUA'] = new_text9
        data['totalMachine'] = new_text10
        data['UPH'] = new_text11
        # Write updated data back to data.json
        with open('data.json', 'w') as file:
            json.dump(data, file, indent=4)
        
    def apply_setting(self):
        self.updateconfig()
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("Thiết lập thành công!")
        msg.setWindowTitle("Thông báo")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.exec_()
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())